apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: node-nodevfile-nodocker-rhtap-three-component-scenarios-3huv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hpuy-tenant/mc-three-scenarios/node-nodevfile-nodocker-rhtap-three-component-scenarios-3huv@sha256:d916b86fcc4914c5da88538aa369a85c4b6b04ee9ea53e6e1447ea1247320765
        name: my-nodejs
        resources: {}
status: {}
